name: Build Unreal Plugin

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout plugin source
        uses: actions/checkout@v4

      - name: Checkout Unreal Engine
        uses: actions/checkout@v4
        with:
          repository: GloryOfNight/UnrealEngine
          token: ${{ secrets.UE_REPO }} # must have access to UE repo
          path: UE

      - name: Setup Unreal dependencies
        shell: powershell
        working-directory: UE
        run: |
          ./Setup.bat
          ./GenerateProjectFiles.bat

      - name: Build Plugin
        shell: powershell
        run: |
          & UE\Engine\Build\BatchFiles\RunUAT.bat BuildPlugin ^
            -Plugin="$PWD/UnrealRCon.uplugin" ^
            -Package="$PWD/Package" ^
            -Rocket ^
            -TargetPlatforms=Win64
